
// ********RoostGPT********
/*
Test generated by RoostGPT for test urvi_testing_java using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=handleEntityNotFoundException_14c9acbf43
ROOST_METHOD_SIG_HASH=handleEntityNotFoundException_14c9acbf43


Scenario 1: Validate ResponseEntity with Proper Error Details for EntityNotFoundException

Details:
  TestName: validateResponseEntityOnEntityNotFoundException
  Description: This test ensures that the method returns a ResponseEntity object with the correct error details, including HTTP status, error message, and additional info when an EntityNotFoundException is thrown.

Execution:
  Arrange: Create a mock EntityNotFoundException object with a specific error message.
  Act: Pass the mock exception to the handleEntityNotFoundException method.
  Assert: Verify that the ResponseEntity object contains the expected HTTP status (NOT_FOUND), error message, and other error details (`test`).

Validation:
  The test verifies that the method correctly handles the EntityNotFoundException and returns the appropriate error response, which is crucial for ensuring a predictable behavior when entities are not found in the application.

*/

// ********RoostGPT********

package com.baeldung.web.error;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mockito.Mockito;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import javax.persistence.EntityNotFoundException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

public class GlobalExceptionHandlerControllerHandleEntityNotFoundExceptionTest {

	private final GlobalExceptionHandlerController globalExceptionHandlerController = new GlobalExceptionHandlerController();

	@Test
	@Category(Categories.valid.class)
	public void validateResponseEntityOnEntityNotFoundException() {
		// Arrange
		EntityNotFoundException exception = Mockito.mock(EntityNotFoundException.class);
		Mockito.when(exception.getLocalizedMessage()).thenReturn("Entity not found"); // TODO:
																						// Add
																						// appropriate
																						// message
																						// if
																						// use-case
																						// varies.
		// Act
		ResponseEntity<ApiError> responseEntity = globalExceptionHandlerController
			.handleEntityNotFoundException(exception);
		// Assert
		ApiError apiError = responseEntity.getBody();
		assert apiError != null;
		assert HttpStatus.NOT_FOUND.equals((HttpStatus) apiError.getStatus());
		assert "Entity not found".equals(apiError.getMessage());
		assert "test".equals(apiError.getErrors().get(0));
	}

}