
// ********RoostGPT********
/*
Test generated by RoostGPT for test urvi_testing_java using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=addNewBookToCart_5d0f577e76
ROOST_METHOD_SIG_HASH=addNewBookToCart_7e9ecc9d93

Scenario 1: Successfully add a new book to the cart

Details:
  TestName: successfullyAddNewBookToCart
  Description: Validate that a new book is added to the cart successfully when the provided book's ISBN exists in the repository. The CartResource should return the updated cart details.

Execution:
  Arrange: Set up a mock BookRepository that simulates finding a book by its ISBN. Prepare a NewBookResource object containing valid data.
  Act: Invoke the addNewBookToCart method with the prepared NewBookResource object.
  Assert: Verify that the cart contains the newly added book and the resulting CartResource matches expectations.
Validation:
  Ensure that the book is correctly added to the cart when the ISBN matches a book in the repository. This test confirms the normal functionality of the addNewBookToCart method.

*/

// ********RoostGPT********
package com.baeldung.web.controller;

import com.baeldung.model.Book;
import com.baeldung.model.Cart;
import com.baeldung.persistence.BookRepository;
import com.baeldung.web.error.Checks;
import com.baeldung.web.resource.CartResource;
import com.baeldung.web.resource.NewBookResource;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;
import static org.junit.Assert.*;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import com.baeldung.web.resource.BookResource;

public class CartControllerAddNewBookToCartTest {

	@Mock
	private BookRepository bookRepo;

	@InjectMocks
	private CartController cartController;

	@Before
	public void setUp() {
		MockitoAnnotations.initMocks(this); // Updated method to initialize mocks
		cartController.afterPropertiesSet(); // Initialize the cart
	}

	@Category(Categories.valid.class)
	@Test
	public void successfullyAddNewBookToCart() {
		// Arrange
		String validIsbn = "123456789";
		Book mockBook = new Book();
		mockBook.setIsbn(validIsbn);
		NewBookResource newBookResource = new NewBookResource(mockBook); // Updated
																			// constructor
																			// usage
		when(bookRepo.findByIsbn(validIsbn)).thenReturn(mockBook);
		// Act
		CartResource cartResource = cartController.addNewBookToCart(newBookResource);
		// Assert
		assertNotNull(cartResource);
		assertEquals(1, cartResource.getBooks().size());
		assertEquals(validIsbn, cartResource.getBooks().get(0).getIsbn());
	}

	@Category(Categories.invalid.class)
	@Test(expected = IllegalArgumentException.class)
	public void addNewBookToCartWithInvalidIsbn() {
		// Arrange
		String invalidIsbn = "InvalidISBN";
		Book invalidBook = new Book();
		invalidBook.setIsbn(invalidIsbn);
		NewBookResource newBookResource = new NewBookResource(invalidBook); // Updated
																			// constructor
																			// usage
		when(bookRepo.findByIsbn(invalidIsbn)).thenReturn(null);
		// Act
		cartController.addNewBookToCart(newBookResource);
		// Assert
		verify(bookRepo).findByIsbn(invalidIsbn);
	}

}