
// ********RoostGPT********
/*
Test generated by RoostGPT for test urvi_testing_java using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=root_abbe3c9d1b
ROOST_METHOD_SIG_HASH=root_6c9771e4b2


Scenario 1: Ensure the root method returns a new RootResource object

Details:
  TestName: testRootReturnsNewResource
  Description: This test verifies that the root method correctly creates and returns a new instance of the `RootResource` object when invoked.

Execution:
  Arrange: None required because the method does not take any arguments or depend on external services or resources.
  Act: Call the `root` method from the `RootController` class.
  Assert: Use JUnit assertions to check that the returned object is not null and is an instance of `RootResource`.

Validation:
  This assertion ensures that the `root` method meets its fundamental contract by returning a new instance. This guarantees proper behavior when the endpoint is accessed.

*/

// ********RoostGPT********

package com.baeldung.web.controller;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import com.baeldung.web.resource.RootResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

public class RootControllerRootTest {

	// TEST CASE: Ensure the root method returns a new RootResource object
	@Test
	@Category(Categories.valid.class)
	public void testRootReturnsNewResource() {
		// Arrange: Instantiate the controller class
		RootController rootController = new RootController();

		// Act: Call the method being tested
		RootResource result = rootController.root();

		// Assert: Validate the output
		assertNotNull("Expected non-null result", result);
		assertTrue("Expected the result to be an instance of RootResource", result instanceof RootResource);
	}

}